// <auto-generated />
using System;
using BankConsoleApp.DataAccess.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankConsoleApp.DataAccess.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20230215011900_initDB")]
    partial class initDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BankConsoleApp.Core.Models.Account", b =>
                {
                    b.Property<uint>("AccountNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("Balance")
                        .HasColumnType("float");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AccountNumber");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("BankConsoleApp.Core.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<uint>("AccountNumber")
                        .HasColumnType("int unsigned");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("Mount")
                        .HasColumnType("float");

                    b.HasKey("TransactionNumber");

                    b.HasIndex("AccountNumber");

                    b.ToTable("Trasactions", (string)null);
                });

            modelBuilder.Entity("BankConsoleApp.Core.Models.Transaction", b =>
                {
                    b.HasOne("BankConsoleApp.Core.Models.Account", "AccountNumberNavigation")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountNumberNavigation");
                });

            modelBuilder.Entity("BankConsoleApp.Core.Models.Account", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
